add sign-in token api
clerk/clerk-sdk-go pull request #340
Opened 2024-10-22 19:14 UTC by PhilippBuschhaus

Add the sign-in token api: 
https://clerk.com/docs/reference/backend-api/tag/Sign-in-Tokens

2024-10-23 06:28 UTC, gkats requested changes
Thank you so much for the contribution @PhilippBuschhaus!

Overall the code looks great. I've left a few comments, could you please take another look and then we can :shipit:.

2024-10-23 06:28 UTC, gkats commented on sign_in_token.go
> +	URL       string `json:"url,omitempty"`
I think the URL can also be `null`.

```suggestion
	URL       *string `json:"url,omitempty"`
```

2024-10-23 06:28 UTC, gkats commented on signintokens/client.go
> +package signintokens
:wrench: Let's change the package name (and the folder) to `signintoken`. Most of the package names in the library use singular form for the resources.

2024-10-23 06:28 UTC, gkats commented on signintokens/client.go
> +// Package session provides the Sign In Token API.
```suggestion
// Package signintoken provides the Sign In Token API.
```

2024-10-23 11:55 UTC, PhilippBuschhaus commented
> Thank you so much for the contribution @PhilippBuschhaus!
> 
> Overall the code looks great. I've left a few comments, could you please take another look and then we can :shipit:.

Thanks for the feedback :). I've addressed the issues but let me know if anything else needs changing.

2024-10-23 12:57 UTC, gkats approved these changes

2024-10-23 12:57 UTC, merged

2024-10-25 20:01 UTC, MohamedArif20091999 commented
@PhilippBuschhaus I could see this code is merged, But With latest 	"github.com/clerk/clerk-sdk-go/v2" I'm not able to see this module, Is there something I'm missing here?